

##
# sudo a2enmod proxy proxy_http headers rewrite
# sudo systemctl reload apache2

# Ensure /api proxies to uvicorn
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https"

# Redirect /api -> /api/
RedirectMatch 301 ^/api$ /api/

# Remove /api prefix for the backend
ProxyPass        /api/  http://127.0.0.1:8001/
ProxyPassReverse /api/  http://127.0.0.1:8001/
